FROM python:3-alpine

RUN ["ln", "-sf", "/usr/share/zoneinfo/Asia/Shanghai", "/etc/localtime"]

COPY . /ticket-server/

WORKDIR /ticket-server

RUN pip3 install -r requirements.txt

ENTRYPOINT ["sh", "docker-entrypoint.sh"]
